# Generated by Django 4.0 on 2024-10-04 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='countent',
            new_name='content',
        ),
    ]
